Weather Card
stevenson-space/shs pull request #194
Opened 2023-06-26 04:09 UTC by Aaaaa501

Created a weather card using openmetro weather API (https://open-meteo.com/).
Card looks like this:
<img width="337" alt="Screen Shot 2023-06-25 at 11 08 46 PM" src="https://github.com/stevenson-space/shs/assets/71293864/940d010c-fd50-4eda-a79e-b6887a06dbb6">

2023-06-26 04:23 UTC, JosephShepin requested changes
build failing

2023-06-26 04:23 UTC, JosephShepin commented on src/components/cards/weatherCard.vue
> +  <card v-if="weatherData != null" class="card">
can remove `!= null`

2023-06-26 04:23 UTC, JosephShepin commented on src/components/cards/weatherCard.vue
> +    function formatDate(date) {
add a return type here and can remove eslint disable line

2023-06-26 04:23 UTC, JosephShepin commented on src/components/cards/weatherCard.vue
> +        console.log(dailyData)
remove console logs

2023-06-26 04:23 UTC, JosephShepin commented on src/components/cards/weatherCard.vue
> +        console.error('Error fetching weather data:', error);
also remove console logs. If it fails to fetch, let's hide the card

2023-06-26 04:35 UTC, Aaaaa501 commented
It should work now. Any other issues?

2023-06-26 04:40 UTC, JosephShepin commented
<img width="328" alt="Screenshot 2023-06-25 at 11 39 08 PM" src="https://github.com/stevenson-space/shs/assets/31457361/822a861d-24f9-4ced-ae0e-051f91bde562">
do we need this badge?

2023-06-26 04:40 UTC, JosephShepin commented
is there a way we can show less days? I feel like it's not needed to show 6 days in advance

2023-06-26 04:42 UTC, Aaaaa501 commented
Yeah it would be pretty simple, but how many days do you think is best?

2023-06-26 04:48 UTC, JosephShepin commented
i also feel like we can refine the ui here. i found some ideas on dribble that could help out. I think the icons can be switched out with something more flat looking like the ionicons. I think we can get rid of the "F" for Fahrenheit - everyone uses Fahrenheit so I think it's assumed and just leaving the degree symbol. We could also add a setting for it if we really think people will use celcius. Would it be possible to refine the card to a design similar to the ones below? I think it would be easier to read look cooler. 

<img width="426" alt="Screenshot 2023-06-25 at 11 42 57 PM" src="https://github.com/stevenson-space/shs/assets/31457361/15967fc4-8e11-490e-a7ba-f74327aa765a">
<img width="684" alt="Screenshot 2023-06-25 at 11 44 28 PM" src="https://github.com/stevenson-space/shs/assets/31457361/de8f62b4-6f4a-4bc1-ace9-87031f3605a7">

weather ionicons might look better:
<img width="783" alt="Screenshot 2023-06-25 at 11 45 12 PM" src="https://github.com/stevenson-space/shs/assets/31457361/e0f9f1a3-4d56-4e6f-ac13-aa68d701d881">

2023-06-26 04:56 UTC, JosephShepin commented
Also we are going to want to cache these responses in local storage so we reduce our api calls. Maybe a 6 hour timeout or something around that should be good.

2023-06-26 22:47 UTC, aw-0 commented
Great work, thanks for the PR! On top of the existing comments from joey, would also like to recommend having all of the temperature `<p>`'s be centered for consistency.
![CleanShot 2023-06-26 at 17 44 35](https://github.com/stevenson-space/shs/assets/43796708/cc1257df-a091-4976-8c54-4c63a998ff9c)

Additionally--

> Also we are going to want to cache these responses in local storage so we reduce our api calls. Maybe a 6 hour timeout or something around that should be good.

Could even be possible to do something similar to the calendar where we have it fetch weather data daily (aka on build time) with the calendar updates? Just an idea

2023-06-27 23:30 UTC, Aaaaa501 commented
On the weather ionicons, im not sure how to add ionicons into a vue project. Do you know how?

2023-06-28 20:27 UTC, aw-0 commented
Love those changes! The only other comment I may have is making the current day "Today" instead of the name of the day, causes less confusion when glancing at the UI.

Not sure if joey can comment but I haven't personally worked with ionicons, but looks like there's a [NPM package for Vue](https://www.npmjs.com/package/vue-ionicons). If that doesn't work, here's a [DIY article](https://dev.to/devmount/how-to-use-ionicons-v5-with-vue-js-53g2) you could try that manually adds support through custom elements without a package.

2023-06-30 02:00 UTC, Aaaaa501 commented
Ive added the new features, is the current version good?

Also
> <img alt="Screenshot 2023-06-25 at 11 39 08 PM" width="328" src="https://user-images.githubusercontent.com/31457361/248666227-822a861d-24f9-4ced-ae0e-051f91bde562.png"> do we need this badge?
Yes, I read on the website that they require attribution for usage

2023-07-08 14:13 UTC, JosephShepin commented
This looks really nice. One thing I noticed is that the temperatures are in Celsius - can we make it Fahrenheit?

2023-07-08 14:14 UTC, JosephShepin requested changes
this is really close to being done

2023-07-08 14:14 UTC, JosephShepin commented on src/components/cards/WeatherCard.vue
> +    // localStorage.getItem('weatherDataCache')
i think we can get rid of this line?

2023-07-08 14:36 UTC, JosephShepin approved these changes
Thanks so much! Really nice work! 🥳

2023-07-08 15:40 UTC, Aaaaa501 commented
Does the pull request automatically merge?

2023-07-08 16:11 UTC, JosephShepin commented
@Aaaaa501 feel free to merge whenever

2023-07-08 16:12 UTC, Aaaaa501 commented
I don’t have write access

2023-07-08 16:19 UTC, merged