added themes
stevenson-space/shs pull request #67
Opened 2021-07-04 01:45 UTC by jshepin

2021-07-05 03:20 UTC, jshepin commented
also @abhinavpappu can we settle on a code formatter? I use Beautify and sometimes Prettier. What do you use/want to use going forward? Mismatched formatters screw with stuff sometimes.

2021-07-07 02:33 UTC, abhinavpappu requested changes
Wow this looks amazing! Love how complete it is, especially with the color conflict modal and everything :) Went through all the pages, everything looks great and is consistent 🎉 

Just left a couple minor comments, mostly about adding type definitions. Feel free to ignore any of the comments marked with `nit:`

---

Found one possible bug, here are the steps to reproduce:
1. Switch the color (not the theme)
2. Select a different theme
3. Select "No" in the resulting color conflict
4. Refresh the page


https://user-images.githubusercontent.com/22779056/124691400-67f2d300-dea1-11eb-8048-e57890a71d63.mp4

When the page refreshes, the color switches to the `suggestedColor` of the theme rather than keeping the user selected color. I think this might be due to the `data.choice = 'yes';` at [initializeStore.ts#17](https://github.com/stevenson-space/shs/pull/67/files#diff-470361b9365d8941909af36c7d29b8b9d4c157a81cb956d83ba8194700cf729cR17)

2021-07-07 02:33 UTC, abhinavpappu commented on src/components/Dropdown.vue
>    color: #444
nit: I think this `color` can be removed since we're overriding it in the next line. Or if this is intended to be the default value in case `--tertiary` is not defined, I think we can do `var(--tertiary, #444)` instead

2021-07-07 02:33 UTC, abhinavpappu commented on src/components/Dropdown.vue
>        border-color: white
nit: same thing here and a few more times in this file

2021-07-07 02:33 UTC, abhinavpappu commented on src/data/themes.json
> +    {
Let's add a type definition for this type of object. So something like
```ts
type Theme = {
  name: string;
  suggestedColor: string;
  background: string;
  secondaryBackground: string;
  headerBackgroundColor: string;
  primary: string;
  secondary: string;
  tertiary: string;
  iconTextCardColor: string;
  iconTextCardInvertColor: string;
};
```
could be added to `src\utils\types.ts`

2021-07-07 02:33 UTC, abhinavpappu commented on src/store/initializeStore.ts
> +    const data = { theme: null, choice: '' };
We could also add a type def for this with something like:
```ts
type ThemeData = {
  theme: Theme;
  choice: 'yes' | 'no'; // [brief comment about how choice is used]
};
```
(in `src\utils\types.ts`)

And then this line would change to
```suggestion
    const data: ThemeData = { theme: null, choice: '' };
```

2021-07-07 02:33 UTC, abhinavpappu commented on src/store/initializeStore.ts
> +    const data = { theme: null, choice: '' };
nit: Also maybe rename `choice` to something that makes it's purpose clearer, something like `useThemeColor`/`useCustomColor` with a `boolean` value? Not a huge deal though, especially after we add the type definitions which will enforce the possible values of `yes` and `no`.

2021-07-07 02:33 UTC, abhinavpappu commented on src/store/mutations.ts
> +  setTheme(state, data) { //  'yes':'override', 'no': 'don't override'
After adding the type definition for `ThemeData`,
```suggestion
  setTheme(state, data: ThemeData) { //  'yes':'override', 'no': 'don't override'
```

2021-07-07 02:33 UTC, abhinavpappu commented on src/store/mutations.ts
> +    const { choice } = data;
nit:
```suggestion
    const { theme, choice } = data;
```

2021-07-07 02:33 UTC, abhinavpappu commented on src/store/state.ts
> +import themes from '@/data/themes.json';
I don't think there's a way to add a type to this directly in the import statement, but would recommend doing something like this (after adding the `Theme` type): 
```suggestion
import _themes from '@/data/themes.json';
const themes: Theme[] = _themes;
```

2021-07-07 02:33 UTC, abhinavpappu commented on src/views/Colors/Colors.vue
> +          v-show="color != suggestedColor"
Thanks for getting rid of the hardcoded value!

2021-07-07 02:33 UTC, abhinavpappu commented on src/views/Colors/ThemeCircle.vue
> +      return `linear-gradient( -45deg, ${this.colors[0]}, ${this.colors[0]} 50%, ${this.colors[1]} 50% )`;
nice! this gradient looks really cool!

2021-07-07 02:33 UTC, abhinavpappu commented on src/views/Colors/ThemeCircle.vue
> +    for (x of ['suggestedColor', 'background']) {
nit: Just curious, any reason why `let x;` is declared on a separate line instead of just `for(let x of ...)`?

2021-07-07 02:33 UTC, abhinavpappu commented on src/views/Colors/ThemeCircle.vue
> +      return `linear-gradient( -45deg, ${this.colors[0]}, ${this.colors[0]} 50%, ${this.colors[1]} 50% )`;
nit: Could we do something like the following:
```suggestion
      const { suggestedColor, background } = this.theme;
      return `linear-gradient( -45deg, ${suggestedColor}, ${suggestedColor} 50%, ${background} 50% )`;
```
and then get rid of the `colors` state variable as well as the `mounted()` method below?

It looks like this was made with the original intent of possibly being able to support displaying more of the colors in the theme, but personally I think the current version looks great!

2021-07-07 02:33 UTC, abhinavpappu commented on src/data/themes.json
> +        "headerBackgroundColor": "var(--color)",
Love the use of variables in the JSON! Wouldn't have thought of it myself

2021-07-07 02:33 UTC, abhinavpappu commented on src/views/Colors/ThemeSelector.vue
> +    ...mapState(['color']),
nit:
```suggestion
    ...mapState(['theme', 'color']),
```

2021-07-07 02:33 UTC, abhinavpappu commented on src/views/Colors/ThemeSelector.vue
> +      :newTheme="theme.name == 'light' ? themes[1] : themes[0]"
If it's not too much work, I think it would be better to remove the hard coded values here. At first glance, it seems that `:newTheme="selectedTheme"` would work, but let me know if not

2021-07-07 02:33 UTC, abhinavpappu commented on src/views/Settings/Transfer.vue
> -  'color',
Not sure if I'm fully understanding how the theme state works, but I think we might still want `color` to be a transferable setting in case the user selects a custom color instead of using the one that the theme suggests?

2021-07-07 02:33 UTC, abhinavpappu commented on src/components/cards/DarkModeCard.vue
> +<template>
Not right now, but at some point in the future, I think we should update this card to work with arbitrary themes. I'm sure you were already thinking of doing things like holiday themes, and this card could probably be reused to prompt the user to switch to that theme 😃

2021-07-07 02:37 UTC, abhinavpappu commented
> also @abhinavpappu can we settle on a code formatter? I use Beautify and sometimes Prettier. What do you use/want to use going forward? Mismatched formatters screw with stuff sometimes.

Yep that's a good idea! I've never used Beautify but have used Prettier briefly so I'm leaning slightly towards it, but if you have any preference, we can go with that

2021-07-07 03:46 UTC, jshepin commented on src/views/Settings/Transfer.vue
> -  'color',
> > also @abhinavpappu can we settle on a code formatter? I use Beautify and sometimes Prettier. What do you use/want to use going forward? Mismatched formatters screw with stuff sometimes.
> 
> Yep that's a good idea! I've never used Beautify but have used Prettier briefly so I'm leaning slightly towards it, but if you have any preference, we can go with that

Beautify it is.

2021-07-07 03:48 UTC, jshepin commented
Beautify is great.

2021-07-07 03:55 UTC, jshepin commented on src/components/Dropdown.vue
>        border-color: white
🤦🏻

2021-07-07 03:57 UTC, jshepin commented on src/data/themes.json
> +    {
Ok. I don't actually know typescript. I will see what I can do.

2021-07-07 04:01 UTC, jshepin commented on src/views/Colors/ThemeCircle.vue
> +    for (x of ['suggestedColor', 'background']) {
good idea.

2021-07-07 04:25 UTC, jshepin commented
> Wow this looks amazing! Love how complete it is, especially with the color conflict modal and everything :) Went through all the pages, everything looks great and is consistent 🎉
> 
> Just left a couple minor comments, mostly about adding type definitions. Feel free to ignore any of the comments marked with `nit:`
> 
> Found one possible bug, here are the steps to reproduce:
> 
> 1. Switch the color (not the theme)
> 2. Select a different theme
> 3. Select "No" in the resulting color conflict
> 4. Refresh the page
> 
>  Stevenson.High.School.-.Google.Chrome.2021-07-06.21-27-26.mp4 
> When the page refreshes, the color switches to the `suggestedColor` of the theme rather than keeping the user selected color. I think this might be due to the `data.choice = 'yes';` at [initializeStore.ts#17](https://github.com/stevenson-space/shs/pull/67/files#diff-470361b9365d8941909af36c7d29b8b9d4c157a81cb956d83ba8194700cf729cR17)

Good Catch. Not sure how I didn't see this issue 🤔.

2021-07-07 04:31 UTC, jshepin commented
<img width="487" alt="Screen Shot 2021-07-06 at 11 29 52 PM" src="https://user-images.githubusercontent.com/31457361/124700304-1d2d8700-deb2-11eb-9ce3-89c8f9904369.png">
I'm not sure on the positioning of the themes selector row. It feels a little out of place. Maybe it's just me.

2021-07-07 05:31 UTC, jshepin commented
also, do the dark theme colors look familiar from somewhere?  🤔

2021-07-08 06:00 UTC, abhinavpappu commented on src/data/themes.json
> +    {
No worries! Typescript shouldn't be too bad if you're interested in learning, but I could also just add in the type definitions real quick if you want :)

2021-07-08 06:09 UTC, abhinavpappu commented
> Beautify is great.

Awesome, let's use Beautify then! Is there like a config file or something else we can add to indicate we're using Beautify?

> I'm not sure on the positioning of the themes selector row. It feels a little out of place. Maybe it's just me.

It looks mostly fine to me, but if you have any other ideas, would love to hear them!

> also, do the dark theme colors look familiar from somewhere? 🤔

They do! But i can't remember where, honestly i might just be imagining it after you suggested it

2021-07-09 00:00 UTC, jshepin commented
> > Beautify is great.
> 
> Awesome, let's use Beautify then! Is there like a config file or something else we can add to indicate we're using Beautify?
> 
> > I'm not sure on the positioning of the themes selector row. It feels a little out of place. Maybe it's just me.
> 
> It looks mostly fine to me, but if you have any other ideas, would love to hear them!
> 
> > also, do the dark theme colors look familiar from somewhere? 🤔
> 
> They do! But i can't remember where, honestly i might just be imagining it after you suggested it

<img width="1145" alt="Screen Shot 2021-07-08 at 7 00 28 PM" src="https://user-images.githubusercontent.com/31457361/125004267-cc876c80-e01e-11eb-9fc3-7132c593ffef.png">
how about now

2021-07-09 00:26 UTC, jshepin commented
I've gitignored the `.env` file and instead made a `.env-template`, so you can make your own  after you clone it. Otherwise the `.env` gets committed.

2021-07-09 02:59 UTC, jshepin commented on src/store/initializeStore.ts
> +    const data = { theme: null, choice: '' };
made them booleans. now using `useThemeColor`

2021-07-09 03:41 UTC, jshepin commented
@abhinavpappu should we try enabling the "wiki" feature in github to put the documentation?
https://docs.github.com/en/communities/documenting-your-project-with-wikis

2021-07-09 06:09 UTC, abhinavpappu approved these changes
Awesome! The typescript looks amazing and thanks for adding to the README!

2021-07-09 06:09 UTC, abhinavpappu commented on src/views/Colors/ThemeCircle.vue
> +  },
can we get rid of this now? since we changed the below `gradientString` to not use `colors` anymore

2021-07-09 06:09 UTC, abhinavpappu commented on src/views/Colors/ThemeCircle.vue
> +  },
and this?

2021-07-09 06:12 UTC, abhinavpappu commented
> how about now

nope, i'm still blanking :(

> @abhinavpappu should we try enabling the "wiki" feature in github to put the documentation?

sure that sounds good, i'll enable it and copy the little documentation i have currently over

2021-07-10 00:54 UTC, Chaldron commented
This is fantastic, great work! Thank you @jshepin for all the work you've done on this site and @abhinavpappu for the code reviews.

2021-07-10 04:03 UTC, abhinavpappu commented
@jshepin Everything looks perfect, feel free merge whenever!

2021-07-10 14:27 UTC, jshepin commented
@Chaldron Thanks. 
Did you add this to the env. variables in netlify? It should be fine without it but just to be sure.
`VUE_APP_EDIT_COLORS=false`

Also @abhinavpappu  the dark theme is from discord 🙂

2021-07-11 02:19 UTC, jshepin commented
I'm trying to fix the import logic of themes. I can't figure out what the issue is with the deploy.

2021-07-11 02:32 UTC, abhinavpappu commented
> I'm trying to fix the import logic of themes. I can't figure out what the issue is with the deploy.

@jshepin Don't worry about, it's not caused by this PR since `gh-pages` is also failing. I suspect it's because Netlify said they were deprecating Ubuntu 14.04 for the builds so I switched to Ubuntu 16.04 and that might be breaking something. I'll look into it and fix it

2021-07-11 02:45 UTC, Chaldron commented
> `VUE_APP_EDIT_COLORS=false`

added this to the build environment. looking into the netlify build issues now.

2021-07-11 03:06 UTC, Chaldron commented
I think it's lint issues now causing the build failures.

2021-07-11 03:10 UTC, jshepin commented
![image](https://user-images.githubusercontent.com/31457361/125181574-a0f5b500-e1cb-11eb-9aab-085fd62aca1e.png)
let me see what the lint issue is. I do not have access to any logs.

2021-07-11 03:12 UTC, jshepin commented
oh it's an extra space🤦

2021-07-11 05:42 UTC, jshepin commented
@Chaldron I think there's a way to make the logs public 
https://www.netlify.com/blog/2017/10/31/introducing-public-deploy-logs-for-open-source-sites/

2021-07-11 06:08 UTC, jshepin commented
@Chaldron I think there's a way to make the logs public.
https://www.netlify.com/blog/2017/10/31/introducing-public-deploy-logs-for-open-source-sites/

2021-07-12 22:50 UTC, Chaldron commented
> @Chaldron I think there's a way to make the logs public.
> https://www.netlify.com/blog/2017/10/31/introducing-public-deploy-logs-for-open-source-sites/

@jshepin you should be able to access the logs now. let me know if you can't.

2021-07-13 01:22 UTC, jshepin commented
> @jshepin you should be able to access the logs now. let me know if you can't.

Now they're visible. Thanks

2021-07-13 03:02 UTC, merged